# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'yarn'
    - run: yarn
    - run: yarn build
    - name: Remove Source Maps
      run: rm -rf build/static/**/*.map
    - uses: crazy-max/ghaction-github-pages@v3.0.0
      with:
        build_dir: 'build'
        target_branch: 'build'
        verbose: true
        jekyll: false
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}